server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      ie.citadel: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/


zuul:
  prefix:  /api
  ignored-services: '*'
  routes:
    pupilservice: /pupil/**
    addressservice: /address/**
